### PR TITLE
Improve error handling

### PR DESCRIPTION
**Pull request by JirkaChadima**
Instead of using generic JS errors, this PR introduces a variety of custom Error classes that should allow the users of this library to react more precisely to what is happening in WT platform.

### CODE REVIEW

**Comment by hynek-urban** [comment]
@JirkaChadima This is nice! Definitely a step in the right direction. From the perspective of the library user, though, I still have a few specific problems which I'm not sure I can solve without some further modifications. (This is based on my specific needs in write API, but I think they are not outlandish and could easily apply to other future users of the library.)

Let's take hotel update as an example. I would like to distinguish between these three cases (to be able to return different status codes):

1. Wallet cannot be deciphered with the given password. (401)
2. User is trying to update hotel that belongs to someone else. (403)
3. User has not enough ether / gas to finish the transaction. (422? 402?)
(4. The wallet is somehow mismanaged, e.g. invalid json format or not unlocked before using. (500))

As far as I can tell, all these states are reported as a single error type, namely "WalletError". The possible causes can be narrowed down by context (e.g. when I get "WalletError" after calling "wallet.unlock()", I can assume the problem is either (1) or (4)), but not fully. In effect, I cannot easily distinguish among these cases. 

Do you think these cases could be made distinguishable? Or do I miss some way how to do it with the current implementation? (Or do you think it's not necessary?)

**Comment by JirkaChadima** [comment]
1, 2, 4 can be easily distinguished. I agree with that, I wasn't sure into how much detail I should go.

3. and 5. are a bit more complicated because they are tied to web3 communication with ETH node and its implementation. I can check the ETH balance before, but I'm not sure if I can reliably tell the resulting network cost upfront. As for the network availability/connectability, I'm not sure if I'll be able to reliably tell various errors from web3 apart.

I'll try to dive deeper into web3, but their error management is not that great, from what I've seen so far.

**Comment by hynek-urban** [comment]
@JirkaChadima Thanks!

As far as 5. goes, that one probably isn't that important if it's complicated.

As for 3., I really have no idea how this works, but it appears to be a case that could be relatively common and a one that the user should be able to recover from (by increasing his/her balance and then rerunning the request). That's why I would imagine it should be clearly comunicated to him/her somehow. (The idea of checking balance upfront smells with race conditions though :) )

**Comment by JirkaChadima** [comment]
I've tried my best with what we have in web3.js, but I'm actually not really sure how reliable this is going to be. The changes start at a3f437b, I had to do a rebase because of other merged PRs.

There are also probably some places where the original web3.js errors can leak through (not only when dealing with transactions). I'd deal with them only once we encounter them since they should be pretty specific, I think. Some of the exposed methods are actually only wrapping around an actual call to EVM node.

**Comment by hynek-urban** [comment]
@JirkaChadima Wonderful, thanks.

**Pull request merged**
